# Generated by Django 4.2.11 on 2024-04-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_text_recipe_content_recipe_author_recipe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='A temporary description'),
            preserve_default=False,
        ),
    ]
